type Publisher @model {
    id: Int!
    name: String!
}

type Book @model {
    id: Int!
    title: String!
    publisher_id: Int!
    publisher: Publisher!
}

type Author @model {
    id: Int!
    name: String!
    birthdate: String!
}

type Review @model {
    id: Int!
    content: String!
    book: Book!
}
