type Query {
    characterList: [Character]
    characterById (id : ID!): Character
    planetById (id: ID! = 1): Planet
    planetList: [Planet]
    }

type Character {
        id : ID,
        name : String,
        type: String,
        homePlanet: Int,
        primaryFunction: String @authorize
}

type Planet {
    id : ID,
    name : String
}
