type Character @model(name:"Character") {
    id : ID,
    name : String,
    type: String,
    homePlanet: Int,
    primaryFunction: String
}

type planet @model(name:"Planet"){
    id : ID,
    name : String,
    character: Character,
    age : Int,
    dimension : String,
    stars: [Star]
}

type Star @model(name:"Star"){
    id : ID,
    name : String
}
