type Character @model {
    id : ID,
    name : String,
    type: String,
    homePlanet: Int,
    primaryFunction: String
}

type Planet @model {
    id : ID,
    name : String,
    character: Character,
    age : Int,
    dimension : String,
    stars: [Star]
}

type Star @model {
    id : ID,
    name : String
}
