# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04' # examples of other options: 'macOS-10.15', 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Install dotnet format
  inputs:
    command: custom
    custom: tool
    arguments: 'restore'

- task: DotNetCoreCLI@2
  displayName: Check formatting
  inputs:
    command: custom
    custom: format
    projects: '$(solution)'
    arguments: '--check --fix-whitespace --fix-style warn --fix-analyzers warn'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  displayName: "Run Unit Tests"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--filter "TestCategory!=Cosmos&TestCategory!=MsSql" --configuration $(buildConfiguration)'

# This task gets the current date and saves it to a variable so the docker task can use the build's 
# date and time as a tag.
- task: PowerShell@2
  displayName: "Get date for Docker image Tag"
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Setting up the date and time as a build variable for the Docker tag"
      $date=$(Get-Date -format yyyyMMdd-HHmmss)
      Write-Host "##vso[task.setvariable variable=BuildDate]$date"

# Build a docker image and push it to the container registry. This is a temporary location until
# we close on where we want these images to live.
- task: Docker@2
  displayName: "Build and push docker image to docker hub"
  inputs:
    containerRegistry: 'CosmosDB-GraphQL-TempDockerHub'
    repository: 'matrembl/graphql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(BuildDate)'
