version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/hawaii:latest"
    ports:
      - "5000:5000"
    restart: "no"
    volumes:
      - "./DataGateway.Service/appsettings.mssql.json:/App/appsettings.json"
      - "./DataGateway.Service/todo-sql.json:/App/todo-sql.json"
      - "./DataGateway.Service/todo.gql:/App/todo.gql"
