version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/hawaii:latest"
    ports:
      - "5000:5000"
    volumes:
      - "./DataGateway.Service/appsettings.PostgreSql.json:/App/appsettings.json"
      - "./DataGateway.Service/sql-config.json:/App/config.json"
      - "./DataGateway.Service/books.gql:/App/books.gql"
