# MsSql Integration Testing Pipeline config is split into two jobs:
# 1) LinuxTests -> Run SQL Server 2019 in Linux Docker Image
# 2) WindowsTests -> Run LocalDB preinstalled on

trigger:
- main

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      DataGatewayConfig.DatabaseConnection.ConnectionString: $(ConnectionStringSQLExpressVariable)

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'

  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce
      releaseType: stable

  - bash: |
      docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$(DockerSQLpass)" -p 1433:1433 --name customerdb mcr.microsoft.com/mssql/server:2019-latest
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Get and Start Ubuntu SQL Server Image Docker

  - task: FileTransform@1
    displayName: 'Generate appsettings.MsSqlIntegrationTest.json'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      fileType: 'json'
      targetFiles: 'DataGateway.Service/appsettings.MsSqlIntegrationTest.json'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)' # Update this to match your need

  - task: DotNetCoreCLI@2
    displayName: 'Run MsSql Integration Tests'
    inputs:
      command: test
      arguments: '--filter "TestCategory=MsSql" --configuration $(buildConfiguration)'
      projects: '**/*Tests/*.csproj'

- job: windows
  pool:
    vmImage: 'windows-latest'
  variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      DataGatewayConfig.DatabaseConnection.ConnectionString: $(ConnectionStringLocalDBVariable)
      InstallerUrl: https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi
      SqlVersionCode: '15.0'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'

  - task: PowerShell@2
    displayName: Install SQL LocalDB
    inputs:
      targetType: 'inline'
      script: |
        SqlLocalDb.exe start
        SqlLocalDB.exe info "MSSQLLocalDB"
        Write-Host "Downloading"
        Import-Module BitsTransfer
        Start-BitsTransfer -Source $(InstallerUrl) -Destination SqlLocalDB.msi
        Write-Host "Installing"
        Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
        SqlLocalDB.exe stop MSSQLLocalDB -k
        SqlLocalDB.exe delete MSSQLLocalDB

  - task: PowerShell@2
    displayName: 'Start MSSQLLocalDB'
    inputs:
      targetType: 'inline'
      script: |
        SqlLocalDb.exe start MSSQLLocalDB
        SqlLocalDb.exe info "MSSQLLocalDB"

  - task: FileTransform@1
    displayName: 'Generate appsettings.MsSqlIntegrationTest.json'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      fileType: 'json'
      targetFiles: 'DataGateway.Service/appsettings.MsSqlIntegrationTest.json'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)' # Update this to match your need

  - task: DotNetCoreCLI@2
    displayName: 'Run MsSql Integration Tests'
    inputs:
      command: test
      arguments: '--filter "TestCategory=MsSql" --configuration $(buildConfiguration)'
      projects: '**/*Tests/*.csproj'

# This is temporary and will be moved on its own pipeline in the future
- job: postgres_tests_linux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      DataGatewayConfig.DatabaseConnection.ConnectionString: $(ConnectionStringPostgres)

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'

  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce
      releaseType: stable

  - bash: |
      docker run --name postgres-container -p 5432:5432 \
      -e POSTGRES_PASSWORD=$(PostgresPassword) \
      -e POSTGRES_DB=$(TestDatabaseName) \
      -d postgres
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Get and Start Ubuntu Postgres Image Docker

  - task: FileTransform@1
    displayName: 'Generate appsettings.PostgreSqlIntegrationTest.json'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      fileType: 'json'
      targetFiles: 'DataGateway.Service/appsettings.PostgreSqlIntegrationTest.json'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)' # Update this to match your need

  - task: DotNetCoreCLI@2
    displayName: 'Run Postgres Integration Tests'
    inputs:
      command: test
      arguments: '--filter "TestCategory=PostgreSql" --configuration $(buildConfiguration)'
      projects: '**/*Tests/*.csproj'
