type Character @model(name:"Character") {
    id : ID,
    name : String,
    type: String,
    homePlanet: Int,
    primaryFunction: String,
    star: Star
}

type Planet @model(name:"PlanetAlias"){
    id : ID,
    name : String,
    character: Character,
    age : Int,
    dimension : String,
    stars: [Star]
}

type Star {
    id : ID,
    name : String
}
