using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.Json;
using Azure.DataGateway.Service.Exceptions;
using Azure.DataGateway.Service.Models;
using Azure.DataGateway.Services;

namespace Azure.DataGateway.Service.Services
{
    /// <summary>
    /// Class which validates input supplied by a REST request.
    /// </summary>
    public class RequestValidator
    {
        /// <summary>
        /// Validates the given request by ensuring:
        /// - each field to be returned is one of the columns in the table.
        /// - extra fields specified in the body, will be discarded.
        /// </summary>
        /// <param name="context">Request context containing the REST operation fields and their values.</param>
        /// <param name="configurationProvider">Configuration provider that enables referencing DB schema in config.</param>
        /// <exception cref="DatagatewayException"></exception>
        public static void ValidateRequestContext(RestRequestContext context, IMetadataStoreProvider configurationProvider)
        {
            TableDefinition tableDefinition = TryGetTableDefinition(context.EntityName, configurationProvider);

            foreach (string field in context.FieldsToBeReturned)
            {
                if (!tableDefinition.Columns.ContainsKey(field))
                {
                    throw new DatagatewayException(
                        message: "Invalid Column name requested: " + field,
                        statusCode: (int)HttpStatusCode.BadRequest,
                        subStatusCode: DatagatewayException.SubStatusCodes.BadRequest);
                }
            }

            IEnumerable<string> fieldsInRequestBody = context.FieldValuePairsInBody.Keys;

            // Each field that is checked against the DB schema is removed
            // from the hash set of unvalidated fields.
            // At the end, if we end up with extraneous unvalidated fields, we throw error.
            HashSet<string> unValidatedFields = new(fieldsInRequestBody);

            foreach (KeyValuePair<string, ColumnDefinition> column in tableDefinition.Columns)
            {
                if ( // If the column value is not autogenerated, then the body should contain that field.
                    (!column.Value.IsAutoGenerated && context.FieldValuePairsInBody.Keys.Contains(column.Key))
                    ||
                    // If the column value is autogenerated, then the body should NOT contain that field.
                    (column.Value.IsAutoGenerated && !context.FieldValuePairsInBody.Keys.Contains(column.Key)))
                {
                     // Since the field is now validated, remove it from the unvalidated fields.
                        // containing a value for it in the request body is valid.
                        unValidatedFields.Remove(column.Key);
                }
                else
                {
                    throw new DatagatewayException(
                        message: "Invalid request body. Either insufficient or unnecessary values for fields supplied.",
                        statusCode: (int)HttpStatusCode.BadRequest,
                        subStatusCode: DatagatewayException.SubStatusCodes.BadRequest);
                }
            }

            // TO DO: If the request header contains x-ms-must-match custom header with value of "ignore"
            // this should not throw any error. Tracked by issue #158.
            if (unValidatedFields.Any())
            {
                throw new DatagatewayException(
                    message: "Invalid request body. Either insufficient or extra fields supplied.",
                    statusCode: (int)HttpStatusCode.BadRequest,
                    subStatusCode: DatagatewayException.SubStatusCodes.BadRequest);
            }
        }

        /// <summary>
        /// Tries to validate the primary key in the request match those specified in the entity
        /// definition in the configuration file.
        /// </summary>
        /// <param name="context">Request context containing the primary keys and their values.</param>
        /// <param name="configurationProvider">Configuration provider that enables referencing DB schema in config.</param>
        /// <exception cref="DatagatewayException"></exception>
        public static void ValidatePrimaryKey(RestRequestContext context, IMetadataStoreProvider configurationProvider)
        {
            TableDefinition tableDefinition = TryGetTableDefinition(context.EntityName, configurationProvider);

            int countOfPrimaryKeysInSchema = tableDefinition.PrimaryKey.Count;
            int countOfPrimaryKeysInRequest = context.PrimaryKeyValuePairs.Count;

            if (countOfPrimaryKeysInRequest != countOfPrimaryKeysInSchema)
            {
                throw new DatagatewayException(
                    message: "Primary key column(s) provided do not match DB schema.",
                    statusCode: (int)HttpStatusCode.BadRequest,
                    DatagatewayException.SubStatusCodes.BadRequest);
            }

            // Verify each primary key is present in the table definition.
            List<string> primaryKeysInRequest = new(context.PrimaryKeyValuePairs.Keys);
            IEnumerable<string> missingKeys = primaryKeysInRequest.Except(tableDefinition.PrimaryKey);

            if (missingKeys.Any())
            {
                throw new DatagatewayException(
                    message: $"The request is invalid since the primary keys: " +
                        string.Join(", ", missingKeys) +
                        " requested were not found in the entity definition.",
                        statusCode: (int)HttpStatusCode.BadRequest,
                        DatagatewayException.SubStatusCodes.BadRequest);
            }
        }

        /// <summary>
        /// Validates the request body and queryString with respect to an Insert operation.
        /// </summary>
        /// <param name="queryString">Query string from the url.</param>
        /// <param name="requestBody">The string JSON body from the request.</param>
        /// <exception cref="DatagatewayException"></exception>
        public static JsonElement ValidateInsertRequest(string queryString, string requestBody)
        {
            if (!string.IsNullOrEmpty(queryString))
            {
                throw new DatagatewayException(
                    message: "Query string for POST requests is an invalid url.",
                    statusCode: (int)HttpStatusCode.BadRequest,
                    subStatusCode: DatagatewayException.SubStatusCodes.BadRequest);
            }

            JsonElement insertPayloadRoot = new();

            if (!string.IsNullOrEmpty(requestBody))
            {
                using JsonDocument insertPayload = JsonDocument.Parse(requestBody);

                if (insertPayload.RootElement.ValueKind == JsonValueKind.Array)
                {
                    throw new NotSupportedException("InsertMany operations are not yet supported.");
                }
                else
                {
                    insertPayloadRoot = insertPayload.RootElement.Clone();
                }
            }

            return insertPayloadRoot;
        }

        /// <summary>
        /// Tries to get the table definition for the given entity from the configuration provider.
        /// </summary>
        /// <param name="entityName">Target entity name.</param>
        /// <param name="configurationProvider">Configuration provider that
        /// enables referencing DB schema in config.</param>
        /// <exception cref="DatagatewayException"></exception>

        private static TableDefinition TryGetTableDefinition(string entityName, IMetadataStoreProvider configurationProvider)
        {
            TableDefinition tableDefinition = configurationProvider.GetTableDefinition(entityName);
            if (tableDefinition == null)
            {
                throw new DatagatewayException(
                    message: $"TableDefinition for Entity: {entityName} does not exist.",
                    statusCode: (int)HttpStatusCode.BadRequest,
                    subStatusCode: DatagatewayException.SubStatusCodes.BadRequest);
            }

            return tableDefinition;
        }

    }
}
