using System.Text.Json.Serialization;

namespace Azure.DataGateway.Config
{
    /// <summary>
    /// Indicates the settings are globally applicable.
    /// </summary>
    public record GlobalSettings;

    /// <summary>
    /// Indicates the settings are for the all the APIs.
    /// </summary>
    /// <param name="Path">The URL path at which the API is available.</param>
    /// <param name="Enabled">If the API is enabled.</param>
    public record ApiSettings
        (bool Enabled = true, string Path = "")
        : GlobalSettings();

    /// <summary>
    /// Holds the global settings used at runtime for REST Apis.
    /// </summary>
    /// <param name="Path">The URL prefix path at which endpoints
    /// for all entities will be exposed.</param>
    /// <param name="Enabled">If REST endpoints are enabled.
    /// If set to false, no REST endpoint will be exposed.
    /// If set to true, REST endpoint will be exposed
    /// unless the rest property within an entity configuration is set to false.</param>
    public record RestGlobalSettings
        (bool Enabled, string Path)
        : ApiSettings(Enabled, Path);

    /// <summary>
    /// Holds the global settings used at runtime for GraphQL.
    /// </summary>
    /// <param name="Path">The URL path at which the graphql endpoint will be exposed.</param>
    /// <param name="Enabled">if the GraphQL endpoint is enabled.
    /// If set to true, the defined GraphQL entities will be exposed unless
    /// the GraphQL property within an entity configuration is set to false.</param>
    /// <param name="AllowIntrospection">Defines if the GraphQL introspection file
    /// will be generated by the runtime. If GraphQL is disabled, this will be ignored.</param>
    public record GraphQLGlobalSettings
        (bool Enabled,
         string Path,
         [property: JsonPropertyName("allow-introspection")]
         bool AllowIntrospection = true)
        : ApiSettings(Enabled, Path);

    /// <summary>
    /// Global settings related to hosting.
    /// </summary>
    /// <param name="Mode">The mode in which runtime is running.</param>
    /// <param name="Cors">Settings related to Cross Origin Resource Sharing.</param>
    /// <param name="Authentication">Authentication configuration properties.</param>
    public record HostGlobalSettings
        (HostModeType Mode,
         Cors? Cors,
         AuthenticationConfig? Authentication)
        : GlobalSettings();

    /// <summary>
    /// Configuration related to Cross Origin Resource Sharing (CORS).
    /// </summary>
    /// <param name="Origins">List of Allowed origins.</param>
    /// <param name="AllowCredentials">
    /// Whether to set Access-Control-Allow-Credentials CORS header.</param>
    public record Cors(string[]? Origins,
        [property: JsonPropertyName("allow-credentials")]
        bool AllowCredentials = true);

    /// <summary>
    /// Different runtime configuration types.
    /// </summary>
    public enum GlobalSettingsType
    {
        Rest,
        GraphQL,
        Host
    }

    /// <summary>
    /// Different modes in which the runtime can run.
    /// </summary>
    public enum HostModeType
    {
        Development,
        Production
    }
}
