version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/dab/refs/heads/main:latest"
    ports:
      - "5000:5000"
    volumes:
      - "../src/Service/dab-config.Cosmos.json:/App/dab-config.json"
      - "../src/Service/schema.gql:/App/schema.gql"
