# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/dab/refs/heads/main:latest"
    ports:
      - "5000:5000"
    volumes:
      - "<LOCAL PATH TO THE CONFIG FILE>:/App/dab-config.json"
      - "<LOCAL PATH TO THE SCHEMA FILE>:/App/schema.gql"
