type Query { 
    characterList: [character]
    characterById (id : ID!): character
    planetById (id: ID!): planet
    planetList: [planet]
    } 

type character {
        id : ID, 
        name : String, 
        type: String, 
        homePlanet: Int, 
        primaryFunction: String 
} 

type planet {
    id : ID,
    name : String
}