// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using Azure.DataApiBuilder.Config.ObjectModel;
using Azure.DataApiBuilder.Service.Exceptions;
using Azure.DataApiBuilder.Service.GraphQLBuilder;
using Azure.DataApiBuilder.Service.GraphQLBuilder.Directives;
using HotChocolate.Language;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Azure.DataApiBuilder.Service.Tests.GraphQLBuilder
{
    /// <summary>
    /// Unit tests for the pure static helpers in <see cref="GraphQLUtils"/>.
    /// </summary>
    [TestClass]
    public class GraphQLUtilsTests
    {
        [DataTestMethod]
        [DataRow(DatabaseType.MSSQL, true)]
        [DataRow(DatabaseType.MySQL, true)]
        [DataRow(DatabaseType.DWSQL, true)]
        [DataRow(DatabaseType.PostgreSQL, true)]
        [DataRow(DatabaseType.CosmosDB_PostgreSQL, true)]
        [DataRow(DatabaseType.CosmosDB_NoSQL, false)]
        public void IsRelationalDb(DatabaseType databaseType, bool expected)
        {
            Assert.AreEqual(expected, GraphQLUtils.IsRelationalDb(databaseType));
        }

        [DataTestMethod]
        [DataRow("String", true)]
        [DataRow("Int", true)]
        [DataRow("Boolean", true)]
        [DataRow("ID", true)]
        [DataRow("Book", false)]
        [DataRow("CustomType", false)]
        public void IsBuiltInType(string typeName, bool expected)
        {
            ITypeNode typeNode = new NamedTypeNode(new NameNode(typeName));
            Assert.AreEqual(expected, GraphQLUtils.IsBuiltInType(typeNode));
        }

        [TestMethod]
        public void IsModelType_WithModelDirective_ReturnsTrue()
        {
            ObjectTypeDefinitionNode node = ParseObjectType(@"type Book @model(name: ""Book"") { id: Int }");
            Assert.IsTrue(GraphQLUtils.IsModelType(node));
        }

        [TestMethod]
        public void IsModelType_WithoutModelDirective_ReturnsFalse()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { id: Int }");
            Assert.IsFalse(GraphQLUtils.IsModelType(node));
        }

        [TestMethod]
        public void FindPrimaryKeyFields_CosmosNoSql_ReturnsIdAndPartitionKey()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { title: String }");
            List<FieldDefinitionNode> pkFields = GraphQLUtils.FindPrimaryKeyFields(node, DatabaseType.CosmosDB_NoSQL);

            Assert.AreEqual(2, pkFields.Count);
            CollectionAssert.AreEquivalent(
                new[] { GraphQLUtils.DEFAULT_PRIMARY_KEY_NAME, GraphQLUtils.DEFAULT_PARTITION_KEY_NAME },
                pkFields.ConvertAll(f => f.Name.Value));
        }

        [TestMethod]
        public void FindPrimaryKeyFields_PrimaryKeyDirective_ReturnsDirectiveField()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { book_id: Int @primaryKey title: String }");
            List<FieldDefinitionNode> pkFields = GraphQLUtils.FindPrimaryKeyFields(node, DatabaseType.MSSQL);

            Assert.AreEqual(1, pkFields.Count);
            Assert.AreEqual("book_id", pkFields[0].Name.Value);
        }

        [TestMethod]
        public void FindPrimaryKeyFields_NoDirective_FallsBackToIdField()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { id: Int title: String }");
            List<FieldDefinitionNode> pkFields = GraphQLUtils.FindPrimaryKeyFields(node, DatabaseType.MSSQL);

            Assert.AreEqual(1, pkFields.Count);
            Assert.AreEqual("id", pkFields[0].Name.Value);
        }

        [TestMethod]
        public void FindPrimaryKeyFields_NoDirectiveNoIdField_Throws()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { title: String }");
            DataApiBuilderException ex = Assert.ThrowsException<DataApiBuilderException>(
                () => GraphQLUtils.FindPrimaryKeyFields(node, DatabaseType.MSSQL));

            Assert.AreEqual(DataApiBuilderException.SubStatusCodes.ErrorInInitialization, ex.SubStatusCode);
        }

        [TestMethod]
        public void IsAutoGeneratedField_WithDirective_ReturnsTrue()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { id: Int @autoGenerated }");
            Assert.IsTrue(GraphQLUtils.IsAutoGeneratedField(node.Fields[0]));
        }

        [TestMethod]
        public void IsAutoGeneratedField_WithoutDirective_ReturnsFalse()
        {
            ObjectTypeDefinitionNode node = ParseObjectType("type Book { id: Int }");
            Assert.IsFalse(GraphQLUtils.IsAutoGeneratedField(node.Fields[0]));
        }

        [TestMethod]
        public void CreateAuthorizationDirective_NullRoles_ReturnsFalse()
        {
            bool created = GraphQLUtils.CreateAuthorizationDirectiveIfNecessary(null, out DirectiveNode? directive);
            Assert.IsFalse(created);
            Assert.IsNull(directive);
        }

        [TestMethod]
        public void CreateAuthorizationDirective_EmptyRoles_ReturnsFalse()
        {
            bool created = GraphQLUtils.CreateAuthorizationDirectiveIfNecessary(new List<string>(), out DirectiveNode? directive);
            Assert.IsFalse(created);
            Assert.IsNull(directive);
        }

        [TestMethod]
        public void CreateAuthorizationDirective_ContainsAnonymous_ReturnsFalse()
        {
            bool created = GraphQLUtils.CreateAuthorizationDirectiveIfNecessary(
                new[] { "role1", GraphQLUtils.SYSTEM_ROLE_ANONYMOUS }, out DirectiveNode? directive);
            Assert.IsFalse(created);
            Assert.IsNull(directive);
        }

        [TestMethod]
        public void CreateAuthorizationDirective_WithRoles_ReturnsAuthorizeDirective()
        {
            bool created = GraphQLUtils.CreateAuthorizationDirectiveIfNecessary(
                new[] { "role1", "role2" }, out DirectiveNode? directive);

            Assert.IsTrue(created);
            Assert.IsNotNull(directive);
            Assert.AreEqual(GraphQLUtils.AUTHORIZE_DIRECTIVE, directive!.Name.Value);
            Assert.AreEqual(1, directive.Arguments.Count);
            Assert.AreEqual(GraphQLUtils.AUTHORIZE_DIRECTIVE_ARGUMENT_ROLES, directive.Arguments[0].Name.Value);
        }

        [DataTestMethod]
        [DataRow(SyntaxKind.IntValue, true)]
        [DataRow(SyntaxKind.EnumValue, true)]
        [DataRow(SyntaxKind.ObjectValue, false)]
        public void IsScalarField_ReturnsExpected(SyntaxKind kind, bool expected)
        {
            Assert.AreEqual(expected, GraphQLUtils.IsScalarField(kind));
        }

        [TestMethod]
        public void LinkingEntityName_RoundTripsSourceAndTarget()
        {
            string name = GraphQLUtils.GenerateLinkingEntityName("Book", "Author");
            Tuple<string, string> decoded = GraphQLUtils.GetSourceAndTargetEntityNameFromLinkingEntityName(name);

            Assert.AreEqual("Book", decoded.Item1);
            Assert.AreEqual("Author", decoded.Item2);
            Assert.ThrowsException<ArgumentException>(
                () => GraphQLUtils.GetSourceAndTargetEntityNameFromLinkingEntityName("Book$Author"));
            Assert.ThrowsException<ArgumentException>(
                () => GraphQLUtils.GetSourceAndTargetEntityNameFromLinkingEntityName("LinkingEntity$Book"));
        }

        [TestMethod]
        public void GetFieldNodeForGivenFieldName_ReturnsValueOrThrows()
        {
            List<ObjectFieldNode> fields = new() { new("id", new IntValueNode(7)) };

            Assert.AreEqual(7, ((IntValueNode)GraphQLUtils.GetFieldNodeForGivenFieldName(fields, "id")).ToInt32());
            Assert.ThrowsException<ArgumentException>(() => GraphQLUtils.GetFieldNodeForGivenFieldName(fields, "missing"));
        }

        [TestMethod]
        public void RelationshipHelpers_HandleConfiguredMissingAndAbsentRelationships()
        {
            EntityRelationship relationship = new(
                Cardinality.Many,
                "Author",
                Array.Empty<string>(),
                Array.Empty<string>(),
                "book_author",
                Array.Empty<string>(),
                Array.Empty<string>());
            Entity entity = CreateEntity(new Dictionary<string, EntityRelationship> { ["authors"] = relationship });

            Assert.IsTrue(GraphQLUtils.IsMToNRelationship(entity, "authors"));
            Assert.IsFalse(GraphQLUtils.IsMToNRelationship(entity, "missing"));
            Assert.AreEqual("Author", GraphQLUtils.GetRelationshipTargetEntityName(entity, "Book", "authors"));
            Assert.ThrowsException<DataApiBuilderException>(
                () => GraphQLUtils.GetRelationshipTargetEntityName(entity, "Book", "missing"));
            Assert.ThrowsException<DataApiBuilderException>(
                () => GraphQLUtils.GetRelationshipTargetEntityName(CreateEntity(null), "Book", "authors"));
        }

        [TestMethod]
        public void RelationshipDirective_ExtractsTargetCardinalityAndDirective()
        {
            FieldDefinitionNode field = ParseObjectType(
                "type Book { author: Author @relationship(target: \"Author\", cardinality: \"many\") }").Fields[0];

            Assert.AreEqual("Author", RelationshipDirectiveType.Target(field));
            Assert.AreEqual(Cardinality.Many, RelationshipDirectiveType.Cardinality(field));
            Assert.IsNotNull(RelationshipDirectiveType.GetDirective(field));

            FieldDefinitionNode plainField = ParseObjectType("type Book { author: Author }").Fields[0];
            Assert.AreEqual("Author", RelationshipDirectiveType.Target(plainField));
            Assert.ThrowsException<ArgumentException>(() => RelationshipDirectiveType.Cardinality(plainField));
        }

        private static Entity CreateEntity(Dictionary<string, EntityRelationship>? relationships)
        {
            return new Entity(
                Source: new EntitySource("books", EntitySourceType.Table, null, null),
                GraphQL: new EntityGraphQLOptions("Book", "Books"),
                Fields: null,
                Rest: new EntityRestOptions(),
                Permissions: Array.Empty<EntityPermission>(),
                Mappings: null,
                Relationships: relationships);
        }

        private static ObjectTypeDefinitionNode ParseObjectType(string sdl)
        {
            DocumentNode document = Utf8GraphQLParser.Parse(sdl);
            return (ObjectTypeDefinitionNode)document.Definitions[0];
        }
    }
}
