using System;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Primitives;

namespace Azure.DataApiBuilder.Service.Models
{
    public static class HttpContextExtensions
    {
        /// <summary>
        /// Attempting to get a correlationid from headers first
        /// if user has a correlation id passed with the request,
        /// otherwise getting correlation id from http context items
        /// which is generated by CorrelationIdMiddleware
        /// </summary>
        /// <param name="context">http context for current request</param>
        /// <returns>either a GUID or null is returned</returns>
        public static Guid? GetCorrelationId(this HttpContext context)
        {
            Guid correlationId;
            if (context.Request.Headers.TryGetValue(HttpHeaders.CORRELATION_ID, out StringValues correlationIdFromHeader)
                && Guid.TryParse(correlationIdFromHeader, out correlationId))
            {
                return correlationId;
            }

            if (context.Items.TryGetValue(HttpHeaders.CORRELATION_ID, out object? correlationIdItem)
                && Guid.TryParse(correlationIdItem?.ToString(), out correlationId))
            {
                return correlationId;
            }

            return null;
        }
    }
}
