// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.Data;
using Azure.DataApiBuilder.Auth;
using Azure.DataApiBuilder.Config.DatabasePrimitives;
using Azure.DataApiBuilder.Config.ObjectModel;
using Azure.DataApiBuilder.Core.Authorization;
using Azure.DataApiBuilder.Core.Configurations;
using Azure.DataApiBuilder.Core.Models;
using Azure.DataApiBuilder.Core.Resolvers;
using Azure.DataApiBuilder.Core.Services;
using Azure.DataApiBuilder.Core.Services.MetadataProviders;
using Microsoft.AspNetCore.Http;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;

namespace Azure.DataApiBuilder.Service.Tests.UnitTests
{
    [TestClass, TestCategory(TestCategory.MSSQL)]
    public class MsSqlQueryBuilderHelperTests
    {
        private const string ENTITY_NAME = "Book";
        private const string SCHEMA_NAME = "dbo";
        private const string TABLE_NAME = "books";

        private delegate void TryGetColumnCallback(string entity, string field, out string? column);

        private static readonly Dictionary<string, string> _columnMapping = new()
        {
            { "id", "id" },
            { "title", "title" }
        };

        [TestMethod]
        public void BuildInsert_TriggerWithOnlyAutogeneratedPrimaryKeyUsesScopeIdentity()
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition(
                isInsertTriggerEnabled: true,
                isUpdateTriggerEnabled: false,
                isPrimaryKeyAutogenerated: true);
            ISqlMetadataProvider metadataProvider = CreateMetadataProvider(sourceDefinition);
            SqlInsertStructure structure = new(
                ENTITY_NAME,
                metadataProvider,
                CreateAuthorizationResolver(),
                CreateFilterParser(),
                new Dictionary<string, object?> { ["title"] = "The Hobbit" },
                CreateHttpContext());

            string query = new MsSqlQueryBuilder().Build(structure);

            StringAssert.Contains(query, "INSERT INTO [dbo].[books] ([title])");
            StringAssert.Contains(query, "WHERE [dbo].[books].[id] = SCOPE_IDENTITY()");
            Assert.IsFalse(query.Contains("#books_T", StringComparison.Ordinal));
        }

        [DataTestMethod]
        [DataRow(true, false, "OUTPUT Inserted.[id] AS [id]")]
        [DataRow(false, true, "SELECT [id] AS [id], [title] AS [title] from [dbo].[books]")]
        public void BuildUpsert_AsymmetricTriggerConfigurationUsesCorrectOutputQualifier(
            bool isUpdateTriggerEnabled,
            bool isInsertTriggerEnabled,
            string expectedInsertBranch)
        {
            SourceDefinition sourceDefinition = CreateSourceDefinition(
                isInsertTriggerEnabled,
                isUpdateTriggerEnabled,
                isPrimaryKeyAutogenerated: false);
            ISqlMetadataProvider metadataProvider = CreateMetadataProvider(sourceDefinition);
            SqlUpsertQueryStructure structure = new(
                ENTITY_NAME,
                metadataProvider,
                CreateAuthorizationResolver(),
                CreateFilterParser(),
                new Dictionary<string, object?>
                {
                    ["id"] = 1,
                    ["title"] = "The Hobbit"
                },
                incrementalUpdate: false,
                CreateHttpContext());

            string query = new MsSqlQueryBuilder().Build(structure);

            StringAssert.Contains(query, expectedInsertBranch);
        }

        private static SourceDefinition CreateSourceDefinition(
            bool isInsertTriggerEnabled,
            bool isUpdateTriggerEnabled,
            bool isPrimaryKeyAutogenerated)
        {
            SourceDefinition sourceDefinition = new()
            {
                PrimaryKey = new() { "id" },
                IsInsertDMLTriggerEnabled = isInsertTriggerEnabled,
                IsUpdateDMLTriggerEnabled = isUpdateTriggerEnabled
            };
            sourceDefinition.Columns.Add("id", new ColumnDefinition
            {
                SystemType = typeof(int),
                DbType = DbType.Int32,
                IsAutoGenerated = isPrimaryKeyAutogenerated
            });
            sourceDefinition.Columns.Add("title", new ColumnDefinition
            {
                SystemType = typeof(string),
                DbType = DbType.String
            });
            return sourceDefinition;
        }

        private static ISqlMetadataProvider CreateMetadataProvider(SourceDefinition sourceDefinition)
        {
            DatabaseTable table = new(SCHEMA_NAME, TABLE_NAME)
            {
                TableDefinition = sourceDefinition,
                SourceType = EntitySourceType.Table
            };
            Mock<ISqlMetadataProvider> metadataProvider = new();
            metadataProvider.Setup(x => x.EntityToDatabaseObject)
                .Returns(new Dictionary<string, DatabaseObject> { [ENTITY_NAME] = table });
            metadataProvider.Setup(x => x.GetSourceDefinition(ENTITY_NAME)).Returns(sourceDefinition);
            metadataProvider.Setup(x => x.GetDatabaseType()).Returns(DatabaseType.MSSQL);

            string? backingColumn;
            metadataProvider.Setup(x => x.TryGetBackingColumn(It.IsAny<string>(), It.IsAny<string>(), out backingColumn))
                .Callback(new TryGetColumnCallback((string entity, string field, out string? column)
                    => _columnMapping.TryGetValue(field, out column)))
                .Returns((string entity, string field, string? column) => _columnMapping.ContainsKey(field));

            string? exposedColumn;
            metadataProvider.Setup(x => x.TryGetExposedColumnName(It.IsAny<string>(), It.IsAny<string>(), out exposedColumn))
                .Callback(new TryGetColumnCallback((string entity, string field, out string? column)
                    => _columnMapping.TryGetValue(field, out column)))
                .Returns((string entity, string field, string? column) => _columnMapping.ContainsKey(field));

            return metadataProvider.Object;
        }

        private static IAuthorizationResolver CreateAuthorizationResolver()
        {
            Mock<IAuthorizationResolver> authorizationResolver = new();
            authorizationResolver
                .Setup(x => x.ResolveDBPolicy(
                    It.IsAny<string>(),
                    It.IsAny<string>(),
                    It.IsAny<EntityActionOperation>(),
                    It.IsAny<HttpContext>()))
                .Returns(ResolvedDatabasePolicy.Empty);
            return authorizationResolver.Object;
        }

        private static GQLFilterParser CreateFilterParser()
        {
            RuntimeConfigProvider runtimeConfigProvider = TestHelper.GetRuntimeConfigProvider(TestHelper.GetRuntimeConfigLoader());
            Mock<IMetadataProviderFactory> metadataProviderFactory = new();
            return new GQLFilterParser(runtimeConfigProvider, metadataProviderFactory.Object);
        }

        private static DefaultHttpContext CreateHttpContext()
        {
            DefaultHttpContext httpContext = new();
            httpContext.Request.Headers[AuthorizationResolver.CLIENT_ROLE_HEADER] = "authenticated";
            return httpContext;
        }
    }
}
