// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Data;
using Azure.DataApiBuilder.Auth;
using Azure.DataApiBuilder.Config.DatabasePrimitives;
using Azure.DataApiBuilder.Config.ObjectModel;
using Azure.DataApiBuilder.Core.Authorization;
using Azure.DataApiBuilder.Core.Configurations;
using Azure.DataApiBuilder.Core.Models;
using Azure.DataApiBuilder.Core.Resolvers;
using Azure.DataApiBuilder.Core.Services;
using Azure.DataApiBuilder.Core.Services.MetadataProviders;
using Microsoft.AspNetCore.Http;
using Moq;

namespace Azure.DataApiBuilder.Service.Tests.UnitTests
{
    /// <summary>
    /// Creates provider-specific upsert structures for query-builder unit tests without a live database.
    /// </summary>
    internal static class SqlUpsertQueryStructureTestHelper
    {
        internal const string ENTITY_NAME = "Stock";
        internal const string SCHEMA_NAME = "dbo";
        internal const string TABLE_NAME = "stocks";

        private delegate void TryGetColumnCallback(string entity, string field, out string? column);

        private static readonly Dictionary<string, string> _columnMapping = new()
        {
            { "categoryid", "categoryid" },
            { "pieceid", "pieceid" },
            { "categoryName", "categoryName" },
            { "piecesAvailable", "piecesAvailable" }
        };

        /// <summary>
        /// Creates a composite-key upsert structure. Setting <paramref name="hasAutoGeneratedPrimaryKey"/>
        /// produces the update-only fallback shape used by PUT/PATCH for autogenerated keys.
        /// </summary>
        internal static SqlUpsertQueryStructure Create(
            DatabaseType databaseType,
            bool hasAutoGeneratedPrimaryKey = false)
        {
            SourceDefinition sourceDefinition = new()
            {
                PrimaryKey = new() { "categoryid", "pieceid" }
            };
            sourceDefinition.Columns.Add("categoryid", new ColumnDefinition
            {
                SystemType = typeof(int),
                DbType = DbType.Int32,
                IsAutoGenerated = hasAutoGeneratedPrimaryKey
            });
            sourceDefinition.Columns.Add("pieceid", new ColumnDefinition
            {
                SystemType = typeof(int),
                DbType = DbType.Int32
            });
            sourceDefinition.Columns.Add("categoryName", new ColumnDefinition
            {
                SystemType = typeof(string),
                DbType = DbType.String
            });
            sourceDefinition.Columns.Add("piecesAvailable", new ColumnDefinition
            {
                SystemType = typeof(int),
                DbType = DbType.Int32,
                IsNullable = true
            });

            DatabaseTable databaseTable = new(SCHEMA_NAME, TABLE_NAME)
            {
                TableDefinition = sourceDefinition,
                SourceType = EntitySourceType.Table
            };

            Mock<ISqlMetadataProvider> metadataProvider = new();
            metadataProvider.Setup(x => x.EntityToDatabaseObject)
                .Returns(new Dictionary<string, DatabaseObject> { { ENTITY_NAME, databaseTable } });
            metadataProvider.Setup(x => x.GetSourceDefinition(ENTITY_NAME)).Returns(sourceDefinition);
            metadataProvider.Setup(x => x.GetDatabaseType()).Returns(databaseType);

            string? backingColumn;
            metadataProvider.Setup(x => x.TryGetBackingColumn(It.IsAny<string>(), It.IsAny<string>(), out backingColumn))
                .Callback(new TryGetColumnCallback((string entity, string field, out string? column)
                    => _columnMapping.TryGetValue(field, out column)))
                .Returns((string entity, string field, string? column) => _columnMapping.ContainsKey(field));

            string? exposedColumn;
            metadataProvider.Setup(x => x.TryGetExposedColumnName(It.IsAny<string>(), It.IsAny<string>(), out exposedColumn))
                .Callback(new TryGetColumnCallback((string entity, string field, out string? column)
                    => _columnMapping.TryGetValue(field, out column)))
                .Returns((string entity, string field, string? column) => _columnMapping.ContainsKey(field));

            Mock<IAuthorizationResolver> authorizationResolver = new();
            authorizationResolver
                .Setup(x => x.ProcessDBPolicy(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<EntityActionOperation>(), It.IsAny<HttpContext>()))
                .Returns(string.Empty);

            RuntimeConfigProvider runtimeConfigProvider = TestHelper.GetRuntimeConfigProvider(TestHelper.GetRuntimeConfigLoader());
            Mock<IMetadataProviderFactory> metadataProviderFactory = new();
            GQLFilterParser gQLFilterParser = new(runtimeConfigProvider, metadataProviderFactory.Object);

            DefaultHttpContext httpContext = new();
            httpContext.Request.Headers[AuthorizationResolver.CLIENT_ROLE_HEADER] = "authenticated";

            Dictionary<string, object?> mutationParameters = new()
            {
                { "categoryid", 11 },
                { "pieceid", 29 },
                { "categoryName", "SciFi" },
                { "piecesAvailable", 7 }
            };

            return new SqlUpsertQueryStructure(
                entityName: ENTITY_NAME,
                sqlMetadataProvider: metadataProvider.Object,
                authorizationResolver: authorizationResolver.Object,
                gQLFilterParser: gQLFilterParser,
                mutationParams: mutationParameters,
                incrementalUpdate: false,
                httpContext: httpContext);
        }
    }
}
