# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # examples of other options: 'macOS-10.15', 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 0
  minor: 0
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  nugetVersion: '$(major).$(minor).$(patch)-$(Build.BuildId)'
  publishNugetToFeed: $(isNugetRelease)

steps:
- task: UseDotNet@2
  displayName: Setup .NET SDK v6.0.x
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Check formatting
  inputs:
    command: custom
    custom: format
    projects: '$(solution)'
    arguments: '--verify-no-changes'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  displayName: "Run Unit Tests"
  inputs:
    command: test
    projects: '**/*Tests*.csproj'
    arguments: '--filter "TestCategory!=Cosmos&TestCategory!=MsSql&TestCategory!=PostgreSql&TestCategory!=MySql" --configuration $(buildConfiguration) --collect "XPlat Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Creating Nuget Package'
  inputs:
    command: pack
    packagesToPack: '**/Cli.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nupkg'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: nugetVersion
    verbosityPack: 'minimal'

# This task will publish nuget package with build number to pipeline artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish nuget to build Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/nupkg'
    artifactName: 'DataApiBuilder'
    artifactType: 'pipeline'

# This task will authenticate and publish the NuGet Package to internal feed
# To release a new version update the VersionPrefix in Hawaii.Cli.csproj file.
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  condition: eq(variables.publishNugetToFeed, 'true')

- task: NuGetCommand@2
  displayName: 'Publish Nuget to Internal Feed'
  condition: eq(variables.publishNugetToFeed, 'true')
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: CosmosDB/DataApiBuilder
    versioningScheme: 'off'
    allowPackageConflicts: false

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/**/*cobertura.xml'

- task: ShellScript@2
  displayName: "Package build output to multiple platforms"
  inputs:
    scriptPath: publish.sh
    args: $(buildConfiguration)

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  displayName: "Upload build artifacts"
  inputs:
    targetPath: '$(Build.SourcesDirectory)/publish' 

# This task gets the current date and saves it to a variable so the docker task can use the build's
# date and time as a tag.
- task: PowerShell@2
  displayName: "Get date for Docker image Tag"
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Setting up the date and time as a build variable for the Docker tag"
      $date=$(Get-Date -format yyyyMMdd-HHmmss)
      Write-Host "##vso[task.setvariable variable=BuildDate]$date"

# Build a docker image and push it to the container registry.
- task: Docker@2
  displayName: "Build and push docker image to Azure Container Registry"
  condition: eq(variables.publishNugetToFeed, 'false')
  inputs:
    containerRegistry: 'CosmosDB GraphQL/Hawaii'
    repository: 'hawaii/$(Build.SourceBranch)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(BuildDate)-$(Build.SourceVersion)
      latest

# Build a docker image and push it to the container registry.
- task: Docker@2
  displayName: "Build and push docker image to Azure Container Registry"
  condition: eq(variables.publishNugetToFeed, 'true')
  inputs:
    containerRegistry: 'CosmosDB GraphQL/Hawaii'
    repository: 'hawaii/$(Build.SourceBranch)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(releaseName)
