# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- main
strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      ADDITIONAL_TEST_ARGS: '--collect "XPlat Code coverage"'
    mac:
      imageName: "macOS-latest"
      ADDITIONAL_TEST_ARGS: ''
    windows:
      imageName: "windows-2022"
      ADDITIONAL_TEST_ARGS: '--collect "XPlat Code coverage"'
  maxParallel: 3
pool:
  vmImage: $(imageName)
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  displayName: Setup .NET SDK v6.0.x
  inputs:
    packageType: sdk
    version: 6.0.x
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: Pack the CLI tool
  inputs:
    command: pack
    packagesToPack: '**/Hawaii.Cli.csproj' 
    packDirectory: '$(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  displayName: Install the CLI tool
  inputs:
    command: custom
    custom: 'tool install'
    arguments: '-g --add-source $(Build.ArtifactStagingDirectory) hawaii.cli'
- script: cmd < DataGateway.Service/ConfigFiles/CosmosDB_Commands.txt
  workingDirectory: '$(System.DefaultWorkingDirectory)/DataGateway.Service/'
  failOnStderr: true
  condition: eq( variables['Agent.OS'], 'Windows' )
- bash: |
      .**/CosmosDB_Commands.txt
  workingDirectory: './DataGateway.Service/ConfigFiles'
  failOnStderr: true
  condition: in( variables['Agent.OS'], 'Linux', 'macOs' )
- task: FileTransform@1
  displayName: 'Generate hawaii-config.Cosmos.json'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: 'DataGateway.Service/ConfigFiles/hawaii-config.Cosmos.json'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
- task: DotNetCoreCLI@2
  displayName: 'Run Cosmos DB Integration Tests'
  inputs:
    command: test
    arguments: '--filter "TestCategory=Cosmos" --configuration $(buildConfiguration) $(ADDITIONAL_TEST_ARGS)'
    projects: '**/*Tests/*.csproj'

# '/XPlat Code coverage --results-directory /home/vsts/work/1/s/TestResults/'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/**/*cobertura.xml'
