# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- main
strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      ADDITIONAL_TEST_ARGS: '--collect "XPlat Code coverage"'
    mac:
      imageName: "macOS-latest"
      ADDITIONAL_TEST_ARGS: ''
    windows:
      imageName: "windows-2022"
      ADDITIONAL_TEST_ARGS: '--collect "XPlat Code coverage"'
  maxParallel: 3
pool:
  vmImage: $(imageName)
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  
- task: UseDotNet@2
  displayName: Setup .NET SDK v6.0.x
  inputs:
    packageType: sdk
    version: 6.0.x
    
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: Nuget.config

- script: |
    docker pull grafana/k6
    docker run --rm -i grafana/k6 version
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Install k6 tool

- script: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    k6 version
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Install k6 tool

- task: PowerShell@2
  displayName: Install k6 tool
  inputs:
    targetType: 'inline'
    script: |
      Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      k6 version
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- task: FileTransform@1.206.0
  displayName: 'Generate dab-config.Cosmos.json'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: 'src/Service/dab-config.Cosmos.json'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
- task: DotNetCoreCLI@2
  displayName: 'Run Cosmos DB Integration Tests'
  inputs:
    command: test
    arguments: '--filter "TestCategory=Cosmos" --configuration $(buildConfiguration) $(ADDITIONAL_TEST_ARGS)'
    projects: '**/*Tests/*.csproj'

# '/XPlat Code coverage --results-directory /home/vsts/work/1/s/TestResults/'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/**/*cobertura.xml'
