# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# DwSql Integration Testing Pipeline config is split into two jobs:
# 1) LinuxTests -> Run SQL Server 2019 in Linux Docker Image
# 2) WindowsTests -> Run LocalDB preinstalled on machine

trigger:
  batch: true
  branches:
    include:
    - main
    - gh-readonly-queue/main
    - release/*
  paths:
    exclude:
    - docs

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

  steps:
  - task: Bash@3
    displayName: 'Bash generate password'
    inputs:
      targetType: 'inline'
      script: |
        password=$(cat /dev/urandom | tr -dc 'A-Za-z0-9_!@#$%^&*()\-+=' | head -c24)
        echo "##vso[task.setvariable variable=DockerSQLPass;issecret=true]password"
  
  - task: Bash@3
    displayName: 'Bash Check val'
    inputs:
       targetType: 'inline'
       script: |
         echo $(DockerSQLPass)
