# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Hot-Reload Integration Testing Pipeline
# This pipeline runs only hot-reload configuration tests which require longer timeouts
# due to file system watchers and database validation in CI/CD environments.

trigger:
  batch: true
  branches:
    include:
    - main
    - gh-readonly-queue/main
    - release/*
  paths:
    exclude:
    - docs

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - samples/**
    - docs/**
    - '*.md'
    - templates/**

jobs:
- job: windows_hotreload
  displayName: 'Windows Hot-Reload Tests'
  pool:
    vmImage: 'windows-latest'
  variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      # The variable setting on the pipeline UI sets the connection string
      # for the hot-reload tests.
      data-source.connection-string: Server=(localdb)\MSSQLLocalDB;Persist Security Info=False;Integrated Security=True;MultipleActiveResultSets=False;Connection Timeout=5;TrustServerCertificate=True;
      InstallerUrl: https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi
      SqlVersionCode: '15.0'
  timeoutInMinutes: 90

  steps:
  - task: CmdLine@2
    displayName: 'Set flag to publish received files when previous step fails'
    condition: failed()
    inputs:
      script: 'echo ##vso[task.setvariable variable=publishverify]Yes'

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'
  
  # The .NET CLI commands in proceeding tasks use the .NET SDK version specified ("selected") here.
  # Per Microsoft Learn Docs, "Selecting the .NET SDK version is independent from 
  # specifying the runtime version a project targets."
  - task: UseDotNet@2
    displayName: Setup .NET SDK v8.0.x
    inputs:
      packageType: sdk
      version: 8.0.x

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'
      feedsToUse: config
      nugetConfigPath: Nuget.config

  - task: PowerShell@2
    displayName: Install SQL LocalDB
    inputs:
      targetType: 'inline'
      script: |
        SqlLocalDb.exe start
        SqlLocalDB.exe info "MSSQLLocalDB"
        Write-Host "Downloading"
        Import-Module BitsTransfer
        Start-BitsTransfer -Source $(InstallerUrl) -Destination SqlLocalDB.msi
        Write-Host "Installing"
        Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
        SqlLocalDB.exe stop MSSQLLocalDB -k
        SqlLocalDB.exe delete MSSQLLocalDB

  - task: PowerShell@2
    displayName: 'Start MSSQLLocalDB'
    inputs:
      targetType: 'inline'
      script: |
        SqlLocalDb.exe start MSSQLLocalDB
        SqlLocalDb.exe info "MSSQLLocalDB"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: |
        **/*.csproj
        !**/*Tests*.csproj
      arguments: '-p:generateConfigFileForDbType=MsSql --configuration $(buildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Build Test Projects
    inputs:
      command: build
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: FileTransform@1.206.0
    displayName: 'Generate dab-config.MsSql.json'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      fileType: 'json'
      targetFiles: 'src/out/tests/*/dab-config.MsSql.json'

  - task: DotNetCoreCLI@2
    displayName: 'Run Hot-Reload Integration Tests'
    inputs:
      command: test
      arguments: '--filter "TestCategory=MsSql&FullyQualifiedName~ConfigurationHotReloadTests" --no-build --configuration $(buildConfiguration) --collect "XPlat Code coverage" --logger "console;verbosity=detailed" -- RunConfiguration.TestSessionTimeout=5400000'
      projects: '**/*Tests/*.csproj'
    timeoutInMinutes: 80

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/**/*cobertura.xml'

  - task: CopyFiles@2
    condition: eq(variables['publishverify'], 'Yes')
    displayName: 'Copy received files to Artifact Staging'
    inputs:
      contents: '**\*.received.*' 
      targetFolder: '$(Build.ArtifactStagingDirectory)\Verify'
      cleanTargetFolder: true
      overWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish received files as Artifacts'
    name: 'verifypublish'
    condition: eq(variables['publishverify'], 'Yes')
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\Verify'
      ArtifactName: 'Verify'
      publishLocation: 'Container'
