# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

  steps:
  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'

  - task: UseDotNet@2
    displayName: Setup .NET SDK v6.0.x
    inputs:
      packageType: sdk
      version: 6.0.x

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'
      feedsToUse: config
      nugetConfigPath: Nuget.config

  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce
      releaseType: stable

  - bash: |
      docker run --name mysql-container -p 3306:3306 \
      -e MYSQL_ROOT_PASSWORD=$(MySqlPassword) \
      -e MYSQL_DATABASE=$(TestDatabaseName) \
      -d mysql
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Get and Start Ubuntu MySql Image Docker

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)' # Update this to match your need

  - task: FileTransform@1.206.0
    displayName: 'Generate dab-config.MySql.json'
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      fileType: 'json'
      targetFiles: 'src/out/tests/net6.0/dab-config.MySql.json'
      
  - task: DotNetCoreCLI@2
    displayName: 'Run MySql Integration Tests'
    inputs:
      command: test
      arguments: '--filter "TestCategory=MySql" --no-build --configuration $(buildConfiguration) --collect "XPlat Code coverage"'
      projects: '**/*Tests/*.csproj'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/**/*cobertura.xml'
