# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  batch: true
  branches:
    include:
    - main
    - gh-readonly-queue/main
    - release/*

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - samples/**
    - docs/**
    - '*.md'
    - templates/**

pool:
  vmImage: 'ubuntu-latest' # examples of other options: 'macOS-10.15', 'windows-2019'

variables:
- template: templates/variables.yml

steps:
- template: templates/build-pipelines.yml
